# Generated by Django 4.2.5 on 2023-09-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='nomina_aumento_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aumento'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='nomina_piezas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Piezas hechas'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='nomina_sueldo_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sueldo Base'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='nomina_ventas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Venta realizada'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='nomina_aguinaldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aguinaldo'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='nomina_bonificacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bonificacion'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='nomina_bono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bono 14'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='nomina_comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comision'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='nomina_dobles',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Horas dobles'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='nomina_extras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Horas Extras'),
        ),
    ]
