# Generated by Django 4.2.5 on 2023-09-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_aporte_liquidacion_prestamo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='nomina_descuento_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento total'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='nomina_ingreso_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ingreso total'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='nomina_interes',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Interes mensual'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='nomina_neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sueldo Neto'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='nomina_aguinaldo',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Aguinaldo'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='nomina_bono',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Bono 14'),
        ),
    ]
