# Generated by Django 4.2.5 on 2023-09-29 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0023_alter_empleado_empleado_puesto'),
        ('pagos', '0005_alter_nomina_nomina_dobles_calculada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='nomina_departamento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empleados.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='nomina_empleado_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado', verbose_name='Empleado'),
        ),
    ]
