# Generated by Django 4.2.5 on 2023-10-03 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0023_alter_empleado_empleado_puesto'),
        ('pagos', '0008_aporte_aporte_cantidad_aporte_aporte_empleado_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='prestamo_interes',
        ),
        migrations.AddField(
            model_name='aporte',
            name='aporte_acumulado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Acumulado'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='nomina_aporte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aporte total'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='prestamo_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='prestamo_meses',
            field=models.DecimalField(choices=[('6', 'Seis Meses'), ('8', 'Ocho Seis Meses'), ('12', 'Doce Seis Meses')], decimal_places=2, max_digits=10, verbose_name='Tiempo'),
        ),
        migrations.CreateModel(
            name='Igss',
            fields=[
                ('igss_id', models.AutoField(primary_key=True, serialize=False)),
                ('igss_fecha', models.DateTimeField(auto_now_add=True)),
                ('igss_cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto')),
                ('igss_empleado_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado', verbose_name='Empleado')),
            ],
        ),
    ]
