# Generated by Django 4.2.5 on 2023-10-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0009_remove_prestamo_prestamo_interes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='prestamo_mensualidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mensualidades'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='prestamo_meses',
            field=models.DecimalField(choices=[('6', 'Seis Meses'), ('12', 'Ocho Seis Meses'), ('18', 'Doce Seis Meses')], decimal_places=2, max_digits=10, verbose_name='Tiempo'),
        ),
    ]
