# Generated by Django 4.2.5 on 2023-10-04 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0026_alter_empleado_empleado_esposa_and_more'),
        ('pagos', '0010_prestamo_prestamo_mensualidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igss',
            name='igss_empleado_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='prestamo_meses',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tiempo (6, 12 y 18 M)'),
        ),
    ]
