# Generated by Django 4.2.5 on 2023-10-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0012_prestamo_prestamo_aporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='nomina_interes',
        ),
    ]
