# Generated by Django 4.2.5 on 2023-10-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0013_remove_nomina_nomina_interes'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='nomina_interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Interes mensual'),
        ),
    ]
