# Generated by Django 4.2.5 on 2023-10-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0014_nomina_nomina_interes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='nomina_interes',
        ),
        migrations.AlterField(
            model_name='nomina',
            name='nomina_aporte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aporte Solidario'),
        ),
    ]
