# Generated by Django 4.2.5 on 2023-10-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0015_remove_nomina_nomina_interes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='nomina_bonificacion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bonificacion'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='nomina_comision',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Comision'),
        ),
    ]
