# Generated by Django 4.2.5 on 2023-10-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0020_alter_igss_igss_nac'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='liquidacion_ag',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aguinaldo pendiente'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='liquidacion_bn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bono 14 pendiente'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='liquidacion_ind',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Indemnizacion'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='liquidacion_sc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Promedio Sueldo Correspondiente'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='liquidacion_sm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Promedio Sueldo Mensual'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='liquidacion_vc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vacaciones pendientes'),
        ),
    ]
