# Generated by Django 4.2.5 on 2023-10-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0021_liquidacion_liquidacion_ag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='nomina_ausencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ausencia'),
        ),
    ]
