# Generated by Django 4.2.5 on 2023-10-15 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0022_nomina_nomina_ausencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='nomina_fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 14, 22, 47, 2, 586894)),
        ),
    ]
