# Generated by Django 4.2.5 on 2023-10-15 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0023_alter_nomina_nomina_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='nomina_fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 12, 38, 25, 466918)),
        ),
    ]
