# Generated by Django 4.2.5 on 2023-10-15 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0024_alter_nomina_nomina_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='igss',
            options={'verbose_name': 'IGSS', 'verbose_name_plural': 'IGSS'},
        ),
        migrations.AlterField(
            model_name='nomina',
            name='nomina_fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 17, 27, 5, 281337)),
        ),
    ]
