# Generated by Django 4.2.5 on 2023-09-21 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('seccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('seccion_nombre', models.CharField(max_length=50, verbose_name='Nombre de seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('producto_imagen', models.ImageField(blank=True, null=True, upload_to='producto')),
                ('producto_nombre', models.CharField(max_length=50, verbose_name='Nombre de producto')),
                ('producto_descripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('producto_precio', models.FloatField(verbose_name='Precio')),
                ('producto_descuento', models.FloatField(blank=True, null=True, verbose_name='Descuento')),
                ('producto_precio_descuento', models.FloatField(default=0, editable=False, verbose_name='Precio con descuento')),
                ('producto_seccion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tienda.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('compra_id', models.AutoField(primary_key=True, serialize=False)),
                ('compra_fecha', models.DateTimeField(auto_now_add=True)),
                ('compra_cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('compra_preciou', models.FloatField(verbose_name='Precio unitario')),
                ('compra_total', models.FloatField(verbose_name='Total')),
                ('compra_producto_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
    ]
