# Generated by Django 4.2.5 on 2023-09-21 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0006_remove_producto_producto_seccion_delete_compra_and_more'),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='compra_empleado_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado'),
        ),
    ]
