# Generated by Django 4.2.5 on 2023-09-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_compra_compra_producto_id_compraproducto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='compra_cantidad',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='compra_preciou',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='compra_total',
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='compra_cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='compra_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total'),
        ),
    ]
