# Generated by Django 4.2.5 on 2023-09-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_compraproducto_compra_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descuento'),
        ),
    ]
