# Generated by Django 4.2.5 on 2023-09-21 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('departamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('departamento_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('empleado_id', models.AutoField(primary_key=True, serialize=False)),
                ('empleado_estado', models.BooleanField(default=True)),
                ('empleado_contratacion', models.DateTimeField(auto_now_add=True)),
                ('empleado_dpi', models.CharField(max_length=50, verbose_name='DPI')),
                ('empleado_foto', models.ImageField(upload_to='empleados')),
                ('empleado_nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('empleado_apellido', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('empleado_direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('empleado_telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('empleado_correo', models.EmailField(max_length=50, verbose_name='Correo')),
                ('empleado_esposa', models.CharField(max_length=50, verbose_name='Esposa')),
                ('empleado_hijos', models.CharField(max_length=500, verbose_name='Hijos')),
                ('empleado_departamento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empleados.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('seccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('seccion_nombre', models.CharField(max_length=50, verbose_name='Nombre de seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('puesto_id', models.AutoField(primary_key=True, serialize=False)),
                ('puesto_nombre', models.CharField(max_length=50, verbose_name='Nombre de puesto')),
                ('puesto_cantidad', models.IntegerField(verbose_name='Salaraio')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'unique_together': {('puesto_id', 'puesto_cantidad')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('producto_nombre', models.CharField(max_length=50, verbose_name='Nombre de producto')),
                ('producto_descripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('producto_precio', models.IntegerField(verbose_name='Precio')),
                ('producto_descuento', models.IntegerField(verbose_name='Descuento')),
                ('producto_precio_descuento', models.IntegerField(verbose_name='Descuento')),
                ('producto_seccion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empleados.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('nomina_id', models.AutoField(primary_key=True, serialize=False)),
                ('nomina_fecha', models.DateTimeField(auto_now_add=True)),
                ('nomina_extras', models.IntegerField(verbose_name='Horas Extras')),
                ('nomina_dobles', models.IntegerField(verbose_name='Horas dobles')),
                ('nomina_comision', models.IntegerField(verbose_name='Comision')),
                ('nomina_bonificacion', models.IntegerField(verbose_name='Bono')),
                ('nomina_bono', models.IntegerField(verbose_name='Bono')),
                ('nomina_aguinaldo', models.IntegerField(verbose_name='Aguinaldo')),
                ('nomina_empleado_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('expediente_id', models.AutoField(primary_key=True, serialize=False)),
                ('expediente_titulo', models.CharField(max_length=500, verbose_name='Titulos')),
                ('expediente_titulo_foto', models.ImageField(upload_to='expediente')),
                ('expediente_ant_penal', models.ImageField(upload_to='expediente')),
                ('expediente_ant_policiaco', models.ImageField(upload_to='expediente')),
                ('expediente_empleado_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='empleado_puesto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='empleados_puesto', to='Empleados.puesto'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='empleado_salario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='empleados_salario', to='Empleados.puesto'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('compra_id', models.AutoField(primary_key=True, serialize=False)),
                ('compra_fecha', models.DateTimeField(auto_now_add=True)),
                ('compra_cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('compra_preciou', models.IntegerField(verbose_name='Precio unitario')),
                ('compra_total', models.IntegerField(verbose_name='Total')),
                ('compra_empleado_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado')),
                ('compra_producto_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empleados.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('ausencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('ausencia_detalle', models.CharField(max_length=50, verbose_name='Detalle de ausencia')),
                ('ausencia_aprovacion', models.BooleanField(default=False)),
                ('ausencia_desNomina', models.BooleanField(default=False)),
                ('ausencia_descuento', models.IntegerField(verbose_name='Descuento')),
                ('ausencia_empleado_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Aumento',
            fields=[
                ('aumento_id', models.AutoField(primary_key=True, serialize=False)),
                ('aumento_monto', models.IntegerField(verbose_name='Monto')),
                ('aumento_empleado_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado')),
            ],
        ),
    ]
