# Generated by Django 4.2.5 on 2023-09-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_descuento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_precio_descuento',
            field=models.IntegerField(default=0, editable=False, verbose_name='Precio con descuento'),
        ),
    ]
