# Generated by Django 4.2.5 on 2023-09-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0002_alter_producto_producto_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='compra_preciou',
            field=models.FloatField(verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='compra_total',
            field=models.FloatField(verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_descuento',
            field=models.FloatField(blank=True, null=True, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_precio',
            field=models.FloatField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_precio_descuento',
            field=models.FloatField(default=0, editable=False, verbose_name='Precio con descuento'),
        ),
    ]
