# Generated by Django 4.2.5 on 2023-09-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0003_alter_compra_compra_preciou_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='empleado_departamento',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='empleado_puesto',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='empleado_salario',
        ),
    ]
