# Generated by Django 4.2.5 on 2023-09-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0004_remove_empleado_empleado_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_imagen',
            field=models.ImageField(null=True, upload_to='producto'),
        ),
    ]
