# Generated by Django 4.2.5 on 2023-09-21 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0005_producto_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='producto_seccion',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
    ]
