# Generated by Django 4.2.5 on 2023-09-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0012_remove_empleado_empleado_puesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='empleado_departamento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Empleados.departamento'),
        ),
    ]
