# Generated by Django 4.2.5 on 2023-09-23 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0013_empleado_empleado_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='empleado_puesto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empleados.puesto'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='empleado_salario',
            field=models.IntegerField(default=0, verbose_name='Salario'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='puesto_departamento_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Empleados.departamento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empleado_departamento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Empleados.departamento'),
        ),
    ]
