# Generated by Django 4.2.5 on 2023-09-23 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0014_empleado_empleado_puesto_empleado_empleado_salario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='empleado_aumento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Aumento total'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empleado_salario',
            field=models.IntegerField(default=0, editable=False, verbose_name='Salario'),
        ),
        migrations.CreateModel(
            name='Aumento',
            fields=[
                ('aumento_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('aumento_fecha', models.DateTimeField(auto_now_add=True)),
                ('aumento_cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad de aumento')),
                ('aumento_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado')),
            ],
        ),
    ]
