# Generated by Django 4.2.5 on 2023-09-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0015_empleado_empleado_aumento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aumento',
            name='aumento_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
