# Generated by Django 4.2.5 on 2023-09-24 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0016_alter_aumento_aumento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aumento',
            name='aumento_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado', verbose_name='Nombre de empleado y Puesto'),
        ),
        migrations.AlterField(
            model_name='aumento',
            name='aumento_fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de aumento'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='departamento_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empleado_contratacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de contratacion'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empleado_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Empleado'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='puesto_cantidad',
            field=models.IntegerField(verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='puesto_departamento_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Empleados.departamento', verbose_name='Departamento'),
        ),
    ]
