# Generated by Django 4.2.5 on 2023-09-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0017_alter_aumento_aumento_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='empleado_hijos',
            field=models.TextField(verbose_name='Hijos'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='expediente_titulo',
            field=models.TextField(max_length=500, verbose_name='Titulos'),
        ),
    ]
