# Generated by Django 4.2.5 on 2023-09-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0018_alter_empleado_empleado_hijos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='expediente_otros_titulos',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Otros Titulos'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empleado_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empleado_salario',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='expediente_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Expediente de Empleado'),
        ),
    ]
