# Generated by Django 4.2.5 on 2023-09-24 20:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0019_expediente_expediente_otros_titulos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausencia',
            name='ausencia_fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ausencia'),
        ),
        migrations.AlterField(
            model_name='ausencia',
            name='ausencia_aprovacion',
            field=models.BooleanField(default=False, verbose_name='Aprovar Ausencia'),
        ),
        migrations.AlterField(
            model_name='ausencia',
            name='ausencia_desNomina',
            field=models.BooleanField(default=False, verbose_name='Descuento en nomina?'),
        ),
        migrations.AlterField(
            model_name='ausencia',
            name='ausencia_detalle',
            field=models.CharField(max_length=500, verbose_name='Detalle de ausencia'),
        ),
        migrations.AlterField(
            model_name='ausencia',
            name='ausencia_empleado_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='expediente_ant_penal',
            field=models.ImageField(upload_to='expediente', verbose_name='Antecedentes Penales'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='expediente_ant_policiaco',
            field=models.ImageField(upload_to='expediente', verbose_name='Antecedente Policiaco'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='expediente_titulo',
            field=models.TextField(max_length=500, verbose_name='Titulo Principal'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='expediente_titulo_foto',
            field=models.ImageField(upload_to='expediente', verbose_name='Foto de titulo principal'),
        ),
    ]
