# Generated by Django 4.2.5 on 2023-09-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0020_ausencia_ausencia_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausencia',
            name='ausencia_descuento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Descuento'),
        ),
    ]
