# Generated by Django 4.2.5 on 2023-09-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0021_alter_ausencia_ausencia_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausencia',
            name='ausencia_descuento',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Descuento'),
        ),
    ]
