# Generated by Django 4.2.5 on 2023-09-27 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0022_alter_ausencia_ausencia_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='empleado_puesto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empleados.puesto', verbose_name='Puesto'),
        ),
    ]
