# Generated by Django 4.2.5 on 2023-10-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0023_alter_empleado_empleado_puesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='puesto_cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salario'),
        ),
    ]
