# Generated by Django 4.2.5 on 2023-10-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0025_alter_ausencia_ausencia_desnomina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='empleado_esposa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Esposa'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empleado_hijos',
            field=models.TextField(blank=True, null=True, verbose_name='Hijos'),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('departamento_id', 'departamento_nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='puesto',
            unique_together={('puesto_id', 'puesto_nombre')},
        ),
    ]
