# Generated by Django 4.2.5 on 2023-10-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0026_alter_empleado_empleado_esposa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='empleado_esposa',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Esposa'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empleado_hijos',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Hijos'),
        ),
    ]
