# Generated by Django 4.2.5 on 2023-10-14 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0027_alter_empleado_empleado_esposa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expediente',
            old_name='expediente_otros_titulos',
            new_name='expediente_otitulo',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='expediente_ant_penal',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='expediente_ant_policiaco',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='expediente_titulo_foto',
        ),
        migrations.AddField(
            model_name='expediente',
            name='expediente_pdf_cv',
            field=models.FileField(default=None, upload_to='expediente', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Curriculum'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='expediente_pdf_dpi',
            field=models.FileField(default=None, upload_to='expediente', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='DPI'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='expediente_pdf_penal',
            field=models.FileField(default=None, upload_to='expediente', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Antecedentes Penales'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='expediente_pdf_polic',
            field=models.FileField(default=None, upload_to='expediente', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Antecedente Policiaco'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='expediente_pdf_titulo',
            field=models.FileField(default=None, upload_to='expediente', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Foto de titulo principal'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empleado_estado',
            field=models.BooleanField(default=True, verbose_name='O'),
        ),
    ]
