# Generated by Django 4.2.5 on 2023-10-15 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0028_rename_expediente_otros_titulos_expediente_expediente_otitulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ausencia',
            name='ausencia_desNomina',
        ),
        migrations.AlterField(
            model_name='ausencia',
            name='ausencia_aprovacion',
            field=models.BooleanField(default=False, verbose_name='Aprobar Ausencia'),
        ),
        migrations.AlterField(
            model_name='ausencia',
            name='ausencia_empleado_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado', verbose_name='Empleado'),
        ),
    ]
