# Generated by Django 4.2.5 on 2023-10-15 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0029_remove_ausencia_ausencia_desnomina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausencia',
            name='ausencia_fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de ausencia'),
        ),
    ]
