# Generated by Django 4.2.5 on 2023-10-15 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0030_alter_ausencia_ausencia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='aumento',
            name='aumento_desc',
            field=models.CharField(default='', max_length=50, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='aumento',
            name='aumento_cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='aumento',
            name='aumento_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empleado_esposa',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Esposo/a'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empleado_estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='expediente_empleado_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='expediente_titulo',
            field=models.TextField(max_length=150, verbose_name='Titulo'),
        ),
    ]
